--- Wurzelstrang API v1 ---
---
Welcome to the Wurzelstrang API documentation.
---

--
Content Resources
The following are the calls related to the contents of the site
--
PUBLIC CALL: List all entries of your site, that are marked public.
Lists: Name, content, id and position.
GET /entries
< 200
< Content-Type: application/json
{
    "entries": [
        {
            "title": "foo",
            "content": "bla blubb fasel",
            "id": "1",
            "pos": null,
            "levels": "2"
        },
        {
            "title": "bar",
            "content": "fnord",
            "id": "2",
            "pos": "1",
            "levels": "2"
        }
    ]
}

PRIVATE CALL: List all entries of your site, including the private ones.
Lists: Name, public flag, content, id and position.
GET /entries{?apikey}
< 200
< Content-Type: application/json
{
    "entries": [
        {
            "title": "foo",
            "visible": "1",
            "content": "bla blubb fasel",
            "id": "1",
            "pos": null,
            "levels": "2"
        },
        {
            "title": "bar",
            "visible": "",
            "content": "fnord",
            "id": "2",
            "pos": "1",
            "levels": "2"
        }
    ]
}

PUBLIC CALL: List one entry of your site, that is marked public.
Lists: Name, content and id.
GET /entries/{id}
< 200
< Content-Type: application/json
{
    "entry": {
        "title": "foo",
        "content": "bla blubb fasel",
        "id": "1",
        "levels": "2"
    }
}

PRIVATE CALL: List one entry of your site, wether private or public.
Lists: Name, public flag, content, last-edit timestamp and id.
GET /entries/{id?apikey}
< 200
< Content-Type: application/json
{
    "entry": {
        "title": "bar",
        "visible": "",
        "content": "fnord",
        "mtime": null,
        "id": "2",
        "levels": "2"
    }
}

PRIVATE CALL Add a new entry to your site. Returns its ID.
POST /entries
> Content-Type: application/json
{
    "apikey": "fnord",
    "title":"foobar",
    "visible":"1",
    "content":"foo baz"
}
< 201
< Content-Type: application/json
{ "inserted": { "id": 1 } }

PRIVATE CALL Update an entry of your site, addressed by its ID. Returns its ID.
PUT /entries/{id}
> Content-Type: application/json
{
    "apikey": "fnord",
    "title":"foobar",
    "visible":"1",
    "content":"foo baz"
}
< 201
< Content-Type: application/json
{ "updated": { "id": 1 } }

PRIVATE CALL Update an entrys level, addressed by its ID. Returns its ID.
PUT /entries/{id}/level
> Content-Type: application/json
{
    "apikey": "fnord",
    "level":"1"
}
< 201
< Content-Type: application/json
{ "updated": { "id": 1 } }

PRIVATE CALL Update the complete order in which entries can be shown on your site, apart from their ID. Returns nothing.
PUT /entries/neworder
> Content-Type: application/json
{
    "apikey": "fnord",
    "neworder": ["1","2","3","4","5","6","7","8","9"]
}
< 201


-- 
User Resources
The following are the calls related to the admin-user of the site
--

PRIVATE CALL: List user details -> the email-address of his persona-account he wants to login with.
GET /user{?apikey}
< 200
< Content-Type: application/json
{"user":{"user_email":"foo@bar.com"}}

PRIVATE CALL Update user details. Returns its ID.
PUT /user
> Content-Type: application/json
{
    "apikey": "fnord",
    "email": "foo@bar.com"
}
< 201
< Content-Type: application/json
{"user":{"user_email":"foo@bar.com"}}

-- 
Siteinfo Resources
The following are the calls related to the general information about the site
--

PUBLIC CALL: List site information.
List the title that can be use for `<blink>`, the Theme and the headline.
GET /siteinfo
< 200
< Content-Type: application/json
{"siteinfo":{
    "title":"Foobaz", 
    "theme":"Standart", 
    "headline":"Fooo"
}}

PRIVATE CALL Update site information. Returns site same information that was updated.
PUT /siteinfo
> Content-Type: application/json
{
    "apikey": "horst",
    "title": "Foobaz",
    "theme": "Standart",
    "headline": "Fooo"
}
< 201
< Content-Type: application/json
{"siteinfo":{
    "title":"Foobaz", 
    "theme":"Standart", 
    "headline":"Fooo"
}}